import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { getCounrty, COUNTRY_LIST } from "../data";
import { client } from "./_app";

interface ICountry {
  name: string;
  code: string;
}

interface ICountryInfo {
  name: string;
  code: string;
  native: string;
  capital: string;
  currency: string;
  languages : Array<{
    code : string;
    name: string;
  }>
}


export default function Home(props: any) {
  const [countryData, setCountryData] = useState<Array<ICountry>>([]);
  const [country, setCountry] = useState<ICountryInfo>({
    name: "India",
    native: "भारत",
    capital: "New Delhi",
    code: "IN",
    currency: "INR",
    languages: [
      {
        "code": "hi",
        "name": "Hindi"
      },
      {
        "code": "en",
        "name": "English"
      }
    ]
  });
  useEffect( () => {
    new Promise(async (resolve) => {
      const response = await client.query({
          query: COUNTRY_LIST,
        })
        resolve(response);
      })
        .then((res : any) => {
          console.log(res.data);
          setCountryData(res.data.countries);
        })
        .catch((err) => console.log(err.message));

  }, []);
  const SelectCountry = (e: any) => {
    console.log(e.target.value, e.currentTarget.id, e.target.key, e.target.id);
    countryInfoByCode( e.target.value );

  };
  const countryInfoByCode = (countryCode : string) => {
    new Promise((resolve) => {
      const response = client.query({
          query: getCounrty(countryCode),
          variables: { countryCode }
        })
        resolve(response);
      })
        .then((res : any) => {
          console.log(res.data);
          setCountry(res.data.country);
        })
        .catch((err) => console.log(err.message));
  }
  // const { data, loading, error } = useQuery(COUNTRY_LIST);
  // setCountryData(data);
  // console.log(countryData, data);
  // if (loading) return "Loading...";
  // if (error) return <pre>{error.message}</pre>
  return (
    <>
      <Head>
        <title>Country</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Select and get info about country</h1>
          <select value={country.code} onChange={SelectCountry} data-testid = "country-select">
            {countryData.map((country: {name: string, code: string}) => (
              <option key={country.code} value={country.code} id={country.code} data-testid = {country.code}>
                {country.name}
              </option>
            ))}
          </select>
        </div>
        <div>
          <h1>{country.name}</h1>
          <table>
            <tbody>
              <tr><th>Capital:</th><td>{country.capital}</td></tr>
              <tr><th>Native:</th><td>{country.native}</td></tr>
              <tr><th>Currency:</th><td>{country.currency}</td></tr>
                
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
